#:schema node_modules/wrangler/config-schema.json
name = "studio"
compatibility_date = "2024-11-01" 
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAni0m7EgGCdV4yVuXeOxABpr4u38soSS0"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "studio-5183936027-d61dd.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "studio-5183936027-d61dd"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "studio-5183936027-d61dd.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "245185142675"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:245185142675:web:d340c998999d4cbe7e5266"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-1CRY5T19LF"

[compatibility_flags]
compatibility_flags = [ "nodejs_compat" ]
